src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SelectQueries.cls
public class SelectQueries {
	public static List<Account> getAllAccounts()
    {
        List<Account> accountList = new List<account>();
        accountList = [SELECT id FROM Account ];
        
        return accountList;
    }
    //quicker way of returning the list you can just return the query since the object contact already has the list
    public static List<Contact> getAllContacts()
    {
        
        
        return [SELECT id FROM Contact ];
    }
    public static List<Account> getGenePointAccounts()
    {
        return [SELECT Id,Name FROM Account WHERE Name = 'GenePoint'];
        
       
    }
    public static List<Account> getAccountsWithName(string name)
    {
        return [SELECT Id,Name FROM Account WHERE Name=:name];
        
       
    }
    public static List<Student__c> getEnrolledStudents()
    {
        return [SELECT Name FROM Student__c WHERE status__c='Enrolled'];
        
    }
}